services:
  video:
    build:
      context: "../"
      dockerfile: development/Dockerfile
      args:
        DEBUG: "true"
    hostname: video
    container_name: video
    env_file: ../config.env
    volumes:
      - ../:/code
    command: ./scripts/entrypoint.sh
    ports:
     - 8081:8081
