name: ACMI Video Search CI

on: [push]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: acmilabs/video-search
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-video:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Build standard image (cached)
        if: success()
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: "${{ env.DOCKER_REPOSITORY }}"
          image_tag: "${{ env.DOCKER_IMAGE_TAG }}"
          build_extra_args: "--compress=true"

      - name: cancel entire action if failed
        if: failure()
        uses: andymckay/cancel-action@0.2

  build-and-test-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - name: Build Python lint and test
      run: |
        cp config.tmpl.env config.env
        cd development && docker compose -f docker-compose-base.yml up --build -d

    - name: Run Python lint and test
      run: docker exec video make linttest

    - name: cancel entire action if failed
      if: failure()
      uses: andymckay/cancel-action@0.2
